// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"WordWrap","status":true,"description":"Automatically wraps overflowing text.","parameters":{"Word Wrap Style":"break-word"}},
{"name":"HourglassUI","status":true,"description":"Customizations for UI components.","parameters":{}}
];
